sudo: false
git:
  # use depth 2 just in case two refs get pushed at once (like a tag)
  depth: 2
language: ruby
cache: bundler
bundler_args: --path=.bundle/gems
rvm:
- &release_ruby 2.4.1
- 2.1.10
- 2.0.0
- 1.9.3
before_install:
- gem update bundler
- gem cleanup bundler
script: bundle exec gem which prawn
deploy:
  provider: rubygems
  on:
    tags: true
    repo: travis-ci-test
    rvm: *release_ruby
