// ドキュメント表紙
:revnumber: 1.0
:lang: ja
:doctype: book
:docname: Asciidoctor-PDF
:author: park
:revdate: 2018/9/7
:sectnums: 
:chapter-label: 
// Table of Contents
// toc: デフォルトはleft toclevel は目次の表示階層レベル（デフォルト2、最大4）
:toc: 
:toclevels: 2
:toc-title: 目次

// 注脚のアイコン表示
// ①TIP: 補足　②IMPORTANT: 重要.　③WARNING: 警告.　④CAUTION: 注意. ⑤NOTE: ノート
:icons: font

// 画像(jpg)ファイルの相対パス指定
//:imagesdir: ./images
:imagesdir: images

// :source-highlighter: coderay

////
複数行記述分をコメントアウト
する場合に使用します。
////

= asciidoctor PDF

// 改ページ
<<<

・改版履歴

[cols="2,5,4,17", options="header"]
|===

|版数|日付|更新者|内容
|1.0|2018.08.21|FSAS＊＊|新規作成
// |1.1|2018.09.**|FSAS＊＊|3.動作確認

|===

// 改ページ
<<<

.はじめに

== 威厳のあるPDFジェネレータ**Prawn**
Asciidoctor PDFは、Prawnという驚くべきRuby gemによって可能になりました。
そしてgemはどのようなものですか！


Prawnで、テキストを書いたり、線や形を描いたり、ページのどこにでも画像を置いたり、
好きなだけ色を付けたりすることができます。
さらに、印刷可能なドキュメントスペースに流暢なAPIと積極的なコードの再利用をもたらします。

Prawnを使用して基本的なPDF文書を作成する方法を示す例を次に示します。

----
require 'prawn'

Prawn::Document.generate 'output.pdf' do
  text 'Hello, PDF creation!'
end
----

とても簡単です。これはほんの始まりです。使用開始に移る前にスキップしてください。

PrawnはAsciidoctorのこの重要なギャップを埋めるために必要なPDF生成のキラーライブラリです。
AsciiDocからPDF文書を作成する際に苦労しますが、
Prawnは印刷可能な文書の作成にかかる苦労を取り除きます。

== Highlights

* AsciiDocからPDFへの直接変換
* Configuration-driven style and layout
* SVG support
* PDFドキュメント概要（ブックマーク）
* 目次ページ
* ドキュメントのメタデータ（タイトル、著者、件名、キーワードなど）
* 内部相互参照リンク
* ルージュ、Pygments、またはCodeRayでのシンタックスハイライト
* ページ番号
* カスタマイズ可能なコンテンツ（ヘッダーとフッター）
* 複数のブロックを保持する（例えば、特定のブロックコンテンツで回避されるページ区切り）
* 孤立したセクションのタイトルが回避される
* 冗長ブロックの自動修正（base_font_size_min設定で許可されている）
* 正しいテーブルの境界線の設定ができる
* フォントベースのアイコン
* カスタム（TTF）フォント
* 両面印刷モード（余白はアルファベットとベロのページで交互に表示されます: recto and verso pages）

== 前提条件

必要なのは、Ruby（1.9.3以上、2.3.x推奨）といくつかのRuby gemです。
次のセクションでインストール方法を説明します。

Rubyが利用可能かどうかを確認するには、
rubyコマンドを使用してインストールされているバージョンを問い合わせます。
++++
$ ruby --version
++++
[NOTE]
===============================
既定では、Asciidoctor PDFはPrawnがインストールされていない場合、
自動的に最新バージョンのPrawnをインストールします。
古いバージョンのRubyではこれが失敗します。
回避策として、特定の依存関係を先にインストールする必要があります。

Prawn 2.0.0から、インストール中にPrawnはRuby> = 2.0.0を必要とします。
したがって、Ruby 1.9.3でAsciidoctor PDFを使用するには、
まず次の依存関係を明示的にインストールしてバージョンをロックする必要があります。
++++
$ gem install prawn --version 1.3.0
  gem install addressable --version 2.4.0
  gem install prawn-svg --version 0.21.0
  gem install prawn-templates --version 0.0.3
++++
===============================

== システムエンコーディング

AsciidoctorはあなたがUTF-8エンコーディングを使用していると仮定します。
エンコーディングの問題を最小限に抑えるには、
システムのデフォルトエンコーディングがUTF-8に設定されていることを確認してください。

英語以外のWindows環境を使用している場合、
システムのデフォルトのエンコーディングはUTF-8ではない可能性があります。
その結果、Asciidoctorを呼び出すときに、
Encoding :: UndefinedConversionErrorまたは
その他のエンコーディングの問題が発生することがあります。
これらの問題を解決するには、
少なくともコンソールのアクティブなコードページをUTF-8に変更することをお勧めします。

++++
chcp 65001
++++

この変更を行うと、すべてのUnicode問題はなくなります。

== Getting Started

公開されたgemをインストールすることで、Asciidoctor PDFを入手できます。
開発バージョンを使用する場合や開発に参加する場合は、
ソースからコードを実行することもできます。

=== 公開gemをインストールする

Asciidoctor PDFは、RubyGems.orgのプレリリース版として公開されています。
まず、前提条件を満たしていることを確認してください。
次に、公開されたgemを次のコマンドを使用してインストールできます。

++++
$ gem install asciidoctor-pdf --pre
++++

=== サンプルのAsciiDocドキュメント

=== Themes

PDFのレイアウトとスタイリングは、YAML設定ファイルによって駆動されます。
テーマシステムの仕組みとカスタムテーマの作成方法と適用方法については、
Asciidoctor PDF Theme Guideを参照してください。
例として、data / themesディレクトリにある組み込みのテーマファイルを使用することができます。

=== 非ラテン言語のサポート

Asciidoctorは、UTF-8文字セット内のすべての文字を処理できます。
つまり、任意の言語で書類を書いたり、UTF-8エンコーディングでファイルを保存したり、
Asciidoctorでテキストを正しく変換することができます。
ただし、中国語などの特定の言語の特定の文字がPDFに表示されないことがあります。
それに対処する理由と方法については、こちらを参照してください。

ラテン語以外の言語で書いている場合は、
必要なフォントを提供する専用のテーマを使用する必要があります。
たとえば、中国語などのCJK言語で書かれた文書からPDFを作成するには、
CJKテーマを使用する必要があります。
あなたはasciidoctor-pdf-cjk-kai_gen_gothic gemをインストールすることで、
このようなテーマを得ることができます。
詳細な手順については、asciidoctor-pdf-cjk-kai_gen_gothicプロジェクトを参照してください。

=== フォントベースのアイコン

次のアイコンセットのいずれかを使用して、PDFドキュメント内のアイコンを使用できます。

